/**
 * The policy catalogue: everything about it that is not words.
 *
 * Slugs are published URLs, category ids are filter values and anchor
 * targets, and status ids appear in `?status=` — all three would otherwise
 * have been English prose travelling through a query string, which is how a
 * filter link stops working the moment the page is read in another language.
 *
 * `manifestoBasis` and `related` are cross-references between documents, and
 * `lastUpdated` is a date. None of them is a word.
 */

export const policyCategoryIds = [
  "constitutional",
  "family",
  "nation",
  "economy",
  "technology",
  "education",
  "government",
  "healthcare",
  "environment",
  "foreign-policy",
] as const;

export type PolicyCategoryId = (typeof policyCategoryIds)[number];

/** Roman numerals as they appear in the catalogue. */
export const policyCategoryNumerals: Record<PolicyCategoryId, string> = {
  constitutional: "I",
  family: "II",
  nation: "III",
  economy: "IV",
  technology: "V",
  education: "VI",
  government: "VII",
  healthcare: "VIII",
  environment: "IX",
  "foreign-policy": "X",
};

/**
 * How settled a position is, from most to least.
 *
 * The id is what `?status=` carries; the label is in the language files. The
 * catalogue used to filter on the label itself, so `?status=Manifesto%20Core`
 * matched nothing on a translated page.
 */
export const policyStatusIds = [
  "manifesto-core",
  "agreed",
  "derived",
  "open",
] as const;

export type PolicyStatusId = (typeof policyStatusIds)[number];

export interface PolicyEntryStructure {
  readonly slug: string;
  readonly category: PolicyCategoryId;
  readonly status: PolicyStatusId;
  /** A few entries sit between two statuses in the source catalogue. */
  readonly secondaryStatus?: PolicyStatusId;
  /** Manifesto sections this rests on, by `ManifestoSectionData.id`. */
  readonly manifestoBasis?: readonly string[];
  /** Other catalogue entries, by slug. */
  readonly related?: readonly string[];
  /** ISO date, e.g. "2026-09-15". */
  readonly lastUpdated: string;
}

export const policyStructure = [
  {
    slug: "catholic-confessional-state",
    category: "constitutional",
    status: "agreed",
    manifestoBasis: ["moral-order", "democracy"],
    related: [
      "blasphemy-and-sacrilege",
      "state-schools-and-christianity",
      "catholic-medical-ethics",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "abortion",
    category: "constitutional",
    status: "agreed",
    manifestoBasis: ["moral-order", "family"],
    related: [
      "family",
      "euthanasia-and-assisted-suicide",
      "catholic-medical-ethics",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "euthanasia-and-assisted-suicide",
    category: "constitutional",
    status: "agreed",
    manifestoBasis: ["moral-order", "person-not-atom"],
    related: [
      "abortion",
      "universal-healthcare-access",
      "catholic-medical-ethics",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "marriage-and-sexual-ethics",
    category: "constitutional",
    status: "agreed",
    manifestoBasis: ["family", "moral-order"],
    related: ["family", "contraception", "sex-education-in-schools"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "contraception",
    category: "constitutional",
    status: "agreed",
    manifestoBasis: ["family", "moral-order"],
    related: ["family", "demographic-renewal", "sex-education-in-schools"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "pornography",
    category: "constitutional",
    status: "agreed",
    manifestoBasis: ["moral-order", "human-scale-life"],
    related: [
      "prostitution",
      "children-social-media-and-attention-capture",
      "free-speech-and-public-doctrine",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "prostitution",
    category: "constitutional",
    status: "agreed",
    manifestoBasis: ["moral-order", "person-not-atom"],
    related: [
      "pornography",
      "welfare-and-social-assistance",
      "prisons-punishment-and-rehabilitation",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "recreational-drugs",
    category: "constitutional",
    status: "agreed",
    manifestoBasis: ["moral-order", "human-scale-life"],
    related: ["alcohol", "gambling", "prisons-punishment-and-rehabilitation"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "alcohol",
    category: "constitutional",
    status: "agreed",
    manifestoBasis: ["moral-order", "culture"],
    related: ["recreational-drugs", "gambling", "universal-healthcare-access"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "gambling",
    category: "constitutional",
    status: "agreed",
    manifestoBasis: ["moral-order", "finance"],
    related: ["alcohol", "recreational-drugs", "finance-lending-and-usury"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "blasphemy-and-sacrilege",
    category: "constitutional",
    status: "agreed",
    manifestoBasis: ["moral-order", "democracy"],
    related: ["free-speech-and-public-doctrine", "catholic-confessional-state"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "family",
    category: "family",
    status: "manifesto-core",
    manifestoBasis: ["family"],
    related: [
      "marriage-and-sexual-ethics",
      "demographic-renewal",
      "welfare-and-social-assistance",
      "housing-and-financialization",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "demographic-renewal",
    category: "family",
    status: "manifesto-core",
    manifestoBasis: ["family", "immigration"],
    related: [
      "family",
      "immigration",
      "housing-and-financialization",
      "contraception",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "sunday-rest-and-trading",
    category: "family",
    status: "agreed",
    manifestoBasis: ["family", "work", "culture"],
    related: ["work", "family", "catholic-confessional-state"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "welfare-and-social-assistance",
    category: "family",
    status: "agreed",
    manifestoBasis: ["subsidiarity", "family"],
    related: [
      "family",
      "citizenship-general-principle",
      "universal-healthcare-access",
      "authority-democracy-and-subsidiarity",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "nation-and-historical-continuity",
    category: "nation",
    status: "manifesto-core",
    manifestoBasis: ["nation"],
    related: [
      "citizenship-general-principle",
      "immigration",
      "europe-as-a-civilization-of-nations",
      "culture-and-homogenization",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "immigration",
    category: "nation",
    status: "manifesto-core",
    manifestoBasis: ["immigration"],
    related: [
      "asylum-and-international-protection",
      "citizenship-general-principle",
      "naturalization",
      "demographic-renewal",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "asylum-and-international-protection",
    category: "nation",
    status: "agreed",
    manifestoBasis: ["nation", "immigration", "europe", "foreign-policy"],
    related: [
      "immigration",
      "asylum-work-and-public-assistance",
      "deportation-of-criminal-offenders",
      "foreign-aid",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "asylum-work-and-public-assistance",
    category: "nation",
    status: "agreed",
    manifestoBasis: [
      "family",
      "immigration",
      "economic-order",
      "subsidiarity",
      "work",
    ],
    related: [
      "asylum-and-international-protection",
      "welfare-and-social-assistance",
      "work",
      "immigration",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "deportation-of-criminal-offenders",
    category: "nation",
    status: "agreed",
    manifestoBasis: ["nation", "immigration", "subsidiarity", "democracy"],
    related: [
      "immigration",
      "revocation-of-naturalized-citizenship",
      "criminal-sentencing",
      "asylum-and-international-protection",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "citizenship-general-principle",
    category: "nation",
    status: "agreed",
    manifestoBasis: ["nation", "immigration"],
    related: [
      "naturalization",
      "citizenship-by-descent",
      "voting-rights-after-naturalization",
      "dual-citizenship",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "naturalization",
    category: "nation",
    status: "agreed",
    manifestoBasis: ["immigration", "nation"],
    related: [
      "citizenship-general-principle",
      "voting-rights-after-naturalization",
      "dual-citizenship",
      "revocation-of-naturalized-citizenship",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "citizenship-by-descent",
    category: "nation",
    status: "agreed",
    manifestoBasis: ["nation"],
    related: [
      "citizenship-general-principle",
      "naturalization",
      "dual-citizenship",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "voting-rights-after-naturalization",
    category: "nation",
    status: "agreed",
    manifestoBasis: ["democracy", "nation"],
    related: [
      "naturalization",
      "citizenship-general-principle",
      "high-public-office",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "high-public-office",
    category: "nation",
    status: "agreed",
    manifestoBasis: ["nation", "immigration", "subsidiarity", "democracy"],
    related: [
      "voting-rights-after-naturalization",
      "naturalization",
      "authority-democracy-and-subsidiarity",
      "citizenship-by-descent",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "dual-citizenship",
    category: "nation",
    status: "agreed",
    manifestoBasis: ["nation", "europe"],
    related: [
      "naturalization",
      "citizenship-general-principle",
      "europe-as-a-civilization-of-nations",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "revocation-of-naturalized-citizenship",
    category: "nation",
    status: "agreed",
    manifestoBasis: ["nation", "democracy"],
    related: [
      "naturalization",
      "citizenship-general-principle",
      "prisons-punishment-and-rehabilitation",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "europe-as-a-civilization-of-nations",
    category: "nation",
    status: "manifesto-core",
    manifestoBasis: ["europe", "subsidiarity"],
    related: [
      "european-union-institutional-relationship",
      "nation-and-historical-continuity",
      "foreign-policy-doctrine",
      "authority-democracy-and-subsidiarity",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "european-union-institutional-relationship",
    category: "nation",
    status: "agreed",
    manifestoBasis: ["europe", "subsidiarity", "democracy"],
    related: [
      "europe-as-a-civilization-of-nations",
      "authority-democracy-and-subsidiarity",
      "nation-and-historical-continuity",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "economic-order",
    category: "economy",
    status: "manifesto-core",
    manifestoBasis: ["economic-order"],
    related: [
      "private-property-and-broad-ownership",
      "guilds-chambers-and-corporatist-representation",
      "finance-lending-and-usury",
      "work",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "private-property-and-broad-ownership",
    category: "economy",
    status: "manifesto-core",
    manifestoBasis: ["economic-order"],
    related: [
      "economic-order",
      "housing-and-financialization",
      "corporations-and-monopolies",
      "finance-lending-and-usury",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "corporations-and-monopolies",
    category: "economy",
    status: "manifesto-core",
    manifestoBasis: ["economic-order"],
    related: [
      "private-property-and-broad-ownership",
      "economic-order",
      "finance-lending-and-usury",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "guilds-chambers-and-corporatist-representation",
    category: "economy",
    status: "manifesto-core",
    manifestoBasis: ["corporatism", "subsidiarity"],
    related: [
      "economic-order",
      "work",
      "minimum-wage",
      "authority-democracy-and-subsidiarity",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "finance-lending-and-usury",
    category: "economy",
    status: "agreed",
    manifestoBasis: ["finance"],
    related: [
      "housing-and-financialization",
      "private-property-and-broad-ownership",
      "gambling",
      "economic-order",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "housing-and-financialization",
    category: "economy",
    status: "manifesto-core",
    manifestoBasis: ["finance", "architecture"],
    related: [
      "private-property-and-broad-ownership",
      "finance-lending-and-usury",
      "family",
      "architecture-and-historic-preservation",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "work",
    category: "economy",
    status: "manifesto-core",
    manifestoBasis: ["work", "human-scale-life"],
    related: [
      "automation",
      "sunday-rest-and-trading",
      "guilds-chambers-and-corporatist-representation",
      "minimum-wage",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "minimum-wage",
    category: "economy",
    status: "agreed",
    manifestoBasis: ["moral-order", "economic-order", "corporatism", "work"],
    related: [
      "work",
      "guilds-chambers-and-corporatist-representation",
      "trade-unions-and-vocational-representation",
      "taxation",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "taxation",
    category: "economy",
    status: "derived",
    manifestoBasis: [
      "family",
      "economic-order",
      "corporatism",
      "finance",
      "subsidiarity",
    ],
    related: [
      "family",
      "private-property-and-broad-ownership",
      "minimum-wage",
      "pensions",
      "housing-restrictions",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "pensions",
    category: "economy",
    status: "agreed",
    manifestoBasis: [
      "family",
      "economic-order",
      "corporatism",
      "subsidiarity",
      "work",
    ],
    related: [
      "welfare-and-social-assistance",
      "family",
      "guilds-chambers-and-corporatist-representation",
      "taxation",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "housing-restrictions",
    category: "economy",
    status: "derived",
    manifestoBasis: ["family", "economic-order", "finance", "architecture"],
    related: [
      "housing-and-financialization",
      "private-property-and-broad-ownership",
      "architecture-and-historic-preservation",
      "taxation",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "trade-unions-and-vocational-representation",
    category: "economy",
    status: "agreed",
    manifestoBasis: ["economic-order", "corporatism", "subsidiarity", "work"],
    related: [
      "guilds-chambers-and-corporatist-representation",
      "minimum-wage",
      "work",
      "corporations-and-monopolies",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "technology-general-doctrine",
    category: "technology",
    status: "manifesto-core",
    manifestoBasis: ["technology", "human-scale-life"],
    related: [
      "artificial-intelligence",
      "automation",
      "cash-and-non-digital-access",
      "right-to-repair",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "artificial-intelligence",
    category: "technology",
    status: "manifesto-core",
    secondaryStatus: "derived",
    manifestoBasis: ["technology"],
    related: [
      "automation",
      "surveillance",
      "technology-general-doctrine",
      "purpose-of-education",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "automation",
    category: "technology",
    status: "manifesto-core",
    manifestoBasis: ["technology", "work"],
    related: ["work", "artificial-intelligence", "technology-general-doctrine"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "cash-and-non-digital-access",
    category: "technology",
    status: "manifesto-core",
    manifestoBasis: ["human-scale-life", "technology"],
    related: [
      "digital-identification",
      "central-bank-digital-currencies",
      "technology-general-doctrine",
      "surveillance",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "right-to-repair",
    category: "technology",
    status: "manifesto-core",
    manifestoBasis: ["technology", "stewardship"],
    related: [
      "technology-general-doctrine",
      "environmental-stewardship",
      "work",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "surveillance",
    category: "technology",
    status: "manifesto-core",
    secondaryStatus: "derived",
    manifestoBasis: ["human-scale-life", "technology"],
    related: [
      "artificial-intelligence",
      "facial-recognition",
      "communications-metadata-retention",
      "digital-identification",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "children-social-media-and-attention-capture",
    category: "technology",
    status: "manifesto-core",
    secondaryStatus: "derived",
    manifestoBasis: ["family", "technology", "human-scale-life", "education"],
    related: [
      "family",
      "pornography",
      "purpose-of-education",
      "technology-general-doctrine",
      "digital-identification",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "digital-identification",
    category: "technology",
    status: "derived",
    manifestoBasis: ["technology", "human-scale-life"],
    related: [
      "cash-and-non-digital-access",
      "surveillance",
      "central-bank-digital-currencies",
      "technology-general-doctrine",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "central-bank-digital-currencies",
    category: "technology",
    status: "derived",
    manifestoBasis: ["technology", "human-scale-life"],
    related: [
      "cash-and-non-digital-access",
      "digital-identification",
      "cryptocurrency",
      "finance-lending-and-usury",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "cryptocurrency",
    category: "technology",
    status: "derived",
    manifestoBasis: [
      "economic-order",
      "finance",
      "technology",
      "human-scale-life",
    ],
    related: [
      "central-bank-digital-currencies",
      "finance-lending-and-usury",
      "cash-and-non-digital-access",
      "private-property-and-broad-ownership",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "facial-recognition",
    category: "technology",
    status: "derived",
    manifestoBasis: ["technology", "human-scale-life"],
    related: [
      "surveillance",
      "communications-metadata-retention",
      "digital-identification",
      "technology-general-doctrine",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "communications-metadata-retention",
    category: "technology",
    status: "derived",
    manifestoBasis: ["technology", "human-scale-life", "subsidiarity"],
    related: [
      "surveillance",
      "facial-recognition",
      "digital-identification",
      "free-speech-and-public-doctrine",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "genetic-engineering",
    category: "technology",
    status: "derived",
    manifestoBasis: ["moral-order", "person-not-atom", "family", "technology"],
    related: [
      "transhumanism-and-human-enhancement",
      "catholic-medical-ethics",
      "abortion",
      "technology-general-doctrine",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "transhumanism-and-human-enhancement",
    category: "technology",
    status: "derived",
    manifestoBasis: [
      "moral-order",
      "person-not-atom",
      "technology",
      "human-scale-life",
    ],
    related: [
      "genetic-engineering",
      "technology-general-doctrine",
      "artificial-intelligence",
      "catholic-medical-ethics",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "purpose-of-education",
    category: "education",
    status: "manifesto-core",
    manifestoBasis: ["education"],
    related: [
      "state-schools-and-christianity",
      "private-catholic-and-independent-schools",
      "homeschooling",
      "universities-and-academic-freedom",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "homeschooling",
    category: "education",
    status: "agreed",
    manifestoBasis: ["education", "family", "subsidiarity"],
    related: [
      "private-catholic-and-independent-schools",
      "purpose-of-education",
      "sex-education-in-schools",
      "family",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "private-catholic-and-independent-schools",
    category: "education",
    status: "agreed",
    manifestoBasis: ["education", "subsidiarity"],
    related: [
      "homeschooling",
      "state-schools-and-christianity",
      "purpose-of-education",
      "universities-and-academic-freedom",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "universities-and-academic-freedom",
    category: "education",
    status: "agreed",
    manifestoBasis: ["education", "democracy"],
    related: [
      "purpose-of-education",
      "free-speech-and-public-doctrine",
      "private-catholic-and-independent-schools",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "state-schools-and-christianity",
    category: "education",
    status: "agreed",
    manifestoBasis: ["education", "moral-order"],
    related: [
      "catholic-confessional-state",
      "purpose-of-education",
      "private-catholic-and-independent-schools",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "sex-education-in-schools",
    category: "education",
    status: "agreed",
    manifestoBasis: ["education", "family"],
    related: [
      "contraception",
      "homeschooling",
      "marriage-and-sexual-ethics",
      "family",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "culture-and-homogenization",
    category: "education",
    status: "manifesto-core",
    manifestoBasis: ["culture"],
    related: [
      "nation-and-historical-continuity",
      "architecture-and-historic-preservation",
      "purpose-of-education",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "architecture-and-historic-preservation",
    category: "education",
    status: "manifesto-core",
    manifestoBasis: ["architecture"],
    related: [
      "culture-and-homogenization",
      "housing-and-financialization",
      "environmental-stewardship",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "authority-democracy-and-subsidiarity",
    category: "government",
    status: "manifesto-core",
    manifestoBasis: ["subsidiarity", "democracy"],
    related: [
      "free-speech-and-public-doctrine",
      "europe-as-a-civilization-of-nations",
      "welfare-and-social-assistance",
      "high-public-office",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "free-speech-and-public-doctrine",
    category: "government",
    status: "agreed",
    manifestoBasis: ["democracy", "moral-order"],
    related: [
      "blasphemy-and-sacrilege",
      "universities-and-academic-freedom",
      "pornography",
      "authority-democracy-and-subsidiarity",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "prisons-punishment-and-rehabilitation",
    category: "government",
    status: "agreed",
    manifestoBasis: ["moral-order", "democracy"],
    related: [
      "criminal-sentencing",
      "death-penalty",
      "recreational-drugs",
      "firearms-and-self-defense",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "criminal-sentencing",
    category: "government",
    status: "agreed",
    manifestoBasis: [
      "moral-order",
      "person-not-atom",
      "subsidiarity",
      "democracy",
      "what-we-reject",
    ],
    related: [
      "prisons-punishment-and-rehabilitation",
      "death-penalty",
      "capital-punishment-for-aggravated-sexual-crimes",
      "deportation-of-criminal-offenders",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "death-penalty",
    category: "government",
    status: "agreed",
    manifestoBasis: ["moral-order"],
    related: [
      "capital-punishment-for-aggravated-sexual-crimes",
      "prisons-punishment-and-rehabilitation",
      "criminal-sentencing",
      "catholic-confessional-state",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "capital-punishment-for-aggravated-sexual-crimes",
    category: "government",
    status: "agreed",
    manifestoBasis: ["moral-order", "democracy"],
    related: [
      "death-penalty",
      "criminal-sentencing",
      "prisons-punishment-and-rehabilitation",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "firearms-and-self-defense",
    category: "government",
    status: "agreed",
    manifestoBasis: ["subsidiarity", "moral-order"],
    related: [
      "prisons-punishment-and-rehabilitation",
      "authority-democracy-and-subsidiarity",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "universal-healthcare-access",
    category: "healthcare",
    status: "agreed",
    manifestoBasis: ["moral-order", "subsidiarity"],
    related: [
      "catholic-medical-ethics",
      "euthanasia-and-assisted-suicide",
      "welfare-and-social-assistance",
      "abortion",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "catholic-medical-ethics",
    category: "healthcare",
    status: "agreed",
    manifestoBasis: ["moral-order"],
    related: [
      "abortion",
      "euthanasia-and-assisted-suicide",
      "contraception",
      "universal-healthcare-access",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "environmental-stewardship",
    category: "environment",
    status: "manifesto-core",
    manifestoBasis: ["stewardship"],
    related: [
      "energy-policy",
      "climate-policy",
      "right-to-repair",
      "architecture-and-historic-preservation",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "energy-policy",
    category: "environment",
    status: "derived",
    manifestoBasis: ["stewardship", "foreign-policy"],
    related: [
      "nuclear-energy",
      "fossil-fuels",
      "renewable-energy",
      "climate-policy",
      "environmental-stewardship",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "nuclear-energy",
    category: "environment",
    status: "derived",
    manifestoBasis: ["technology", "stewardship", "foreign-policy"],
    related: [
      "energy-policy",
      "fossil-fuels",
      "renewable-energy",
      "nuclear-weapons",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "fossil-fuels",
    category: "environment",
    status: "derived",
    manifestoBasis: ["stewardship", "foreign-policy"],
    related: [
      "energy-policy",
      "nuclear-energy",
      "renewable-energy",
      "climate-policy",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "renewable-energy",
    category: "environment",
    status: "derived",
    manifestoBasis: ["stewardship", "architecture"],
    related: [
      "energy-policy",
      "nuclear-energy",
      "fossil-fuels",
      "architecture-and-historic-preservation",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "climate-policy",
    category: "environment",
    status: "derived",
    manifestoBasis: ["technology", "stewardship", "foreign-policy"],
    related: [
      "energy-policy",
      "environmental-stewardship",
      "fossil-fuels",
      "renewable-energy",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "foreign-policy-doctrine",
    category: "foreign-policy",
    status: "manifesto-core",
    manifestoBasis: ["foreign-policy"],
    related: [
      "europe-as-a-civilization-of-nations",
      "nato",
      "conscription",
      "nuclear-weapons",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "nato",
    category: "foreign-policy",
    status: "derived",
    manifestoBasis: ["foreign-policy", "subsidiarity", "what-we-reject"],
    related: [
      "foreign-policy-doctrine",
      "united-states",
      "russia",
      "conscription",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "russia",
    category: "foreign-policy",
    status: "agreed",
    manifestoBasis: ["foreign-policy"],
    related: ["foreign-policy-doctrine", "ukraine", "nato", "sanctions"],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "ukraine",
    category: "foreign-policy",
    status: "agreed",
    manifestoBasis: ["foreign-policy"],
    related: ["foreign-policy-doctrine", "russia", "nato", "foreign-aid"],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "united-states",
    category: "foreign-policy",
    status: "agreed",
    manifestoBasis: ["europe", "technology", "culture", "foreign-policy"],
    related: [
      "foreign-policy-doctrine",
      "nato",
      "culture-and-homogenization",
      "china",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "china",
    category: "foreign-policy",
    status: "agreed",
    manifestoBasis: ["economic-order", "technology", "foreign-policy"],
    related: [
      "foreign-policy-doctrine",
      "economic-order",
      "united-states",
      "digital-identification",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "israel-and-palestine",
    category: "foreign-policy",
    status: "agreed",
    manifestoBasis: ["foreign-policy", "what-we-reject"],
    related: ["foreign-policy-doctrine", "foreign-aid", "sanctions"],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "foreign-aid",
    category: "foreign-policy",
    status: "derived",
    manifestoBasis: ["moral-order", "immigration", "foreign-policy"],
    related: [
      "foreign-policy-doctrine",
      "asylum-and-international-protection",
      "sanctions",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "sanctions",
    category: "foreign-policy",
    status: "agreed",
    manifestoBasis: ["foreign-policy", "what-we-reject"],
    related: [
      "foreign-policy-doctrine",
      "russia",
      "foreign-aid",
      "israel-and-palestine",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "conscription",
    category: "foreign-policy",
    status: "agreed",
    manifestoBasis: ["person-not-atom", "education", "work", "foreign-policy"],
    related: [
      "foreign-policy-doctrine",
      "nato",
      "purpose-of-education",
      "work",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "nuclear-weapons",
    category: "foreign-policy",
    status: "agreed",
    manifestoBasis: ["foreign-policy", "what-we-reject"],
    related: ["foreign-policy-doctrine", "nato", "nuclear-energy"],
    lastUpdated: "2026-09-21",
  },
] as const satisfies readonly PolicyEntryStructure[];

/**
 * Every slug, as a union. This is what makes a language file's catalogue
 * exhaustive: forget an entry and the build fails rather than one edition
 * quietly publishing eighty-eight positions where the others publish
 * eighty-nine.
 */
export type PolicySlug = (typeof policyStructure)[number]["slug"];
