/**
 * The policy catalogue: everything about it that is not words.
 *
 * Slugs are published URLs and category ids are filter values and anchor
 * targets; both would otherwise have been English prose travelling through a
 * query string, which is how a filter link stops working the moment the page
 * is read in another language.
 *
 * `manifestoBasis` and `related` are cross-references between documents, and
 * `lastUpdated` is a date. None of them is a word.
 */

export const policyCategoryIds = [
  "constitutional",
  "family",
  "nation",
  "economy",
  "technology",
  "education",
  "government",
  "healthcare",
  "environment",
  "foreign-policy",
] as const;

export type PolicyCategoryId = (typeof policyCategoryIds)[number];

/** Roman numerals as they appear in the catalogue. */
export const policyCategoryNumerals: Record<PolicyCategoryId, string> = {
  constitutional: "I",
  family: "II",
  nation: "III",
  economy: "IV",
  technology: "V",
  education: "VI",
  government: "VII",
  healthcare: "VIII",
  environment: "IX",
  "foreign-policy": "X",
};

export interface PolicyEntryStructure {
  readonly slug: string;
  readonly category: PolicyCategoryId;
  /** Manifesto sections this rests on, by `ManifestoSectionData.id`. */
  readonly manifestoBasis?: readonly string[];
  /** Other catalogue entries, by slug. */
  readonly related?: readonly string[];
  /** ISO date, e.g. "2026-09-15". */
  readonly lastUpdated: string;
}

export const policyStructure = [
  {
    slug: "catholic-confessional-state",
    category: "constitutional",
    manifestoBasis: ["moral-order", "democracy"],
    related: [
      "blasphemy-and-sacrilege",
      "state-schools-and-christianity",
      "catholic-medical-ethics",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "abortion",
    category: "constitutional",
    manifestoBasis: ["moral-order", "family"],
    related: [
      "family",
      "euthanasia-and-assisted-suicide",
      "catholic-medical-ethics",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "euthanasia-and-assisted-suicide",
    category: "constitutional",
    manifestoBasis: ["moral-order", "person-not-atom"],
    related: [
      "abortion",
      "universal-healthcare-access",
      "catholic-medical-ethics",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "marriage-and-sexual-ethics",
    category: "constitutional",
    manifestoBasis: ["family", "moral-order"],
    related: ["family", "contraception", "sex-education-in-schools"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "contraception",
    category: "constitutional",
    manifestoBasis: ["family", "moral-order"],
    related: ["family", "demographic-renewal", "sex-education-in-schools"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "pornography",
    category: "constitutional",
    manifestoBasis: ["moral-order", "human-scale-life"],
    related: [
      "prostitution",
      "children-social-media-and-attention-capture",
      "free-speech-and-public-doctrine",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "prostitution",
    category: "constitutional",
    manifestoBasis: ["moral-order", "person-not-atom"],
    related: [
      "pornography",
      "welfare-and-social-assistance",
      "prisons-punishment-and-rehabilitation",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "recreational-drugs",
    category: "constitutional",
    manifestoBasis: ["moral-order", "human-scale-life"],
    related: ["alcohol", "gambling", "prisons-punishment-and-rehabilitation"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "alcohol",
    category: "constitutional",
    manifestoBasis: ["moral-order", "culture"],
    related: ["recreational-drugs", "gambling", "universal-healthcare-access"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "gambling",
    category: "constitutional",
    manifestoBasis: ["moral-order", "finance"],
    related: ["alcohol", "recreational-drugs", "finance-lending-and-usury"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "blasphemy-and-sacrilege",
    category: "constitutional",
    manifestoBasis: ["moral-order", "democracy"],
    related: ["free-speech-and-public-doctrine", "catholic-confessional-state"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "family",
    category: "family",
    manifestoBasis: ["family"],
    related: [
      "marriage-and-sexual-ethics",
      "demographic-renewal",
      "welfare-and-social-assistance",
      "housing-and-financialization",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "demographic-renewal",
    category: "family",
    manifestoBasis: ["family", "immigration"],
    related: [
      "family",
      "immigration",
      "housing-and-financialization",
      "contraception",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "sunday-rest-and-trading",
    category: "family",
    manifestoBasis: ["family", "work", "culture"],
    related: ["work", "family", "catholic-confessional-state"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "welfare-and-social-assistance",
    category: "family",
    manifestoBasis: ["subsidiarity", "family"],
    related: [
      "family",
      "citizenship-general-principle",
      "universal-healthcare-access",
      "authority-democracy-and-subsidiarity",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "nation-and-historical-continuity",
    category: "nation",
    manifestoBasis: ["nation"],
    related: [
      "citizenship-general-principle",
      "immigration",
      "europe-as-a-civilization-of-nations",
      "culture-and-homogenization",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "immigration",
    category: "nation",
    manifestoBasis: ["immigration"],
    related: [
      "asylum-and-international-protection",
      "citizenship-general-principle",
      "naturalization",
      "demographic-renewal",
      "remigration-general-principle",
      "integration-general-definition",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "asylum-and-international-protection",
    category: "nation",
    manifestoBasis: ["nation", "immigration", "europe", "foreign-policy"],
    related: [
      "immigration",
      "asylum-work-and-public-assistance",
      "deportation-of-criminal-offenders",
      "foreign-aid",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "asylum-work-and-public-assistance",
    category: "nation",
    manifestoBasis: [
      "family",
      "immigration",
      "economic-order",
      "subsidiarity",
      "work",
    ],
    related: [
      "asylum-and-international-protection",
      "welfare-and-social-assistance",
      "work",
      "immigration",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "deportation-of-criminal-offenders",
    category: "nation",
    manifestoBasis: ["nation", "immigration", "subsidiarity", "democracy"],
    related: [
      "residence-permit-withdrawal",
      "return-readmission-identity-and-removal-procedure",
      "naturalized-citizenship-and-exceptionally-serious-crime",
      "criminal-sentencing",
      "immigration",
      "asylum-and-international-protection",
    ],
    lastUpdated: "2026-09-23",
  },
  {
    slug: "citizenship-general-principle",
    category: "nation",
    manifestoBasis: ["nation", "immigration"],
    related: [
      "naturalization",
      "citizenship-by-descent",
      "voting-rights-after-naturalization",
      "dual-citizenship",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "naturalization",
    category: "nation",
    manifestoBasis: ["immigration", "nation"],
    related: [
      "citizenship-general-principle",
      "integration-general-definition",
      "probationary-naturalization",
      "voting-rights-after-naturalization",
      "dual-citizenship",
      "revocation-of-naturalized-citizenship",
    ],
    lastUpdated: "2026-09-23",
  },
  {
    slug: "citizenship-by-descent",
    category: "nation",
    manifestoBasis: ["nation"],
    related: [
      "citizenship-general-principle",
      "naturalization",
      "dual-citizenship",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "voting-rights-after-naturalization",
    category: "nation",
    manifestoBasis: ["democracy", "nation"],
    related: [
      "naturalization",
      "citizenship-general-principle",
      "high-public-office",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "high-public-office",
    category: "nation",
    manifestoBasis: ["nation", "immigration", "subsidiarity", "democracy"],
    related: [
      "voting-rights-after-naturalization",
      "naturalization",
      "authority-democracy-and-subsidiarity",
      "citizenship-by-descent",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "dual-citizenship",
    category: "nation",
    manifestoBasis: ["nation", "europe"],
    related: [
      "naturalization",
      "citizenship-general-principle",
      "europe-as-a-civilization-of-nations",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "revocation-of-naturalized-citizenship",
    category: "nation",
    manifestoBasis: ["nation", "democracy"],
    related: [
      "naturalization",
      "probationary-naturalization",
      "naturalized-citizenship-and-exceptionally-serious-crime",
      "citizenship-general-principle",
      "prisons-punishment-and-rehabilitation",
    ],
    lastUpdated: "2026-09-15",
  },
  /*
   * The remigration and enforcement cluster. It sits after the citizenship
   * entries and before Europa because it is the machinery those entries
   * imply, not a separate subject: each entry names one of admission,
   * integration, residence, naturalization or return rather than treating
   * remigration as a single power.
   */
  {
    slug: "remigration-general-principle",
    category: "nation",
    manifestoBasis: ["nation", "immigration", "subsidiarity"],
    related: [
      "immigration",
      "integration-general-definition",
      "residence-permit-withdrawal",
      "return-readmission-identity-and-removal-procedure",
    ],
    lastUpdated: "2026-09-23",
  },
  {
    slug: "integration-general-definition",
    category: "nation",
    manifestoBasis: ["nation", "immigration", "education", "subsidiarity"],
    related: [
      "naturalization",
      "employment-and-self-sufficiency-of-foreign-residents",
      "residence-permit-withdrawal",
      "immigration",
    ],
    lastUpdated: "2026-09-23",
  },
  {
    slug: "regularized-irregular-immigration",
    category: "nation",
    manifestoBasis: ["immigration", "subsidiarity", "democracy"],
    related: [
      "remigration-general-principle",
      "naturalization",
      "probationary-naturalization",
      "residence-permit-withdrawal",
    ],
    lastUpdated: "2026-09-23",
  },
  {
    slug: "employment-and-self-sufficiency-of-foreign-residents",
    category: "nation",
    manifestoBasis: ["economic-order", "work", "immigration"],
    related: [
      "integration-general-definition",
      "asylum-work-and-public-assistance",
      "welfare-and-social-assistance",
      "residence-permit-withdrawal",
    ],
    lastUpdated: "2026-09-23",
  },
  {
    slug: "probationary-naturalization",
    category: "nation",
    manifestoBasis: ["nation", "immigration", "democracy"],
    related: [
      "naturalization",
      "revocation-of-naturalized-citizenship",
      "naturalized-citizenship-and-exceptionally-serious-crime",
      "citizenship-general-principle",
    ],
    lastUpdated: "2026-09-23",
  },
  {
    slug: "residence-permit-withdrawal",
    category: "nation",
    manifestoBasis: ["immigration", "subsidiarity", "democracy"],
    related: [
      "remigration-general-principle",
      "deportation-of-criminal-offenders",
      "integration-general-definition",
      "return-readmission-identity-and-removal-procedure",
    ],
    lastUpdated: "2026-09-23",
  },
  {
    slug: "voluntary-return-and-reintegration",
    category: "nation",
    manifestoBasis: ["immigration", "foreign-policy"],
    related: [
      "return-readmission-identity-and-removal-procedure",
      "remigration-general-principle",
      "deportation-of-criminal-offenders",
      "foreign-aid",
    ],
    lastUpdated: "2026-09-23",
  },
  {
    slug: "naturalized-citizenship-and-exceptionally-serious-crime",
    category: "nation",
    manifestoBasis: ["nation", "immigration", "democracy"],
    related: [
      "revocation-of-naturalized-citizenship",
      "probationary-naturalization",
      "deportation-of-criminal-offenders",
      "criminal-sentencing",
    ],
    lastUpdated: "2026-09-23",
  },
  {
    slug: "return-readmission-identity-and-removal-procedure",
    category: "nation",
    manifestoBasis: [
      "immigration",
      "subsidiarity",
      "democracy",
      "foreign-policy",
    ],
    related: [
      "remigration-general-principle",
      "voluntary-return-and-reintegration",
      "deportation-of-criminal-offenders",
      "asylum-and-international-protection",
    ],
    lastUpdated: "2026-09-23",
  },
  {
    slug: "europe-as-a-civilization-of-nations",
    category: "nation",
    manifestoBasis: ["europe", "subsidiarity"],
    related: [
      "european-union-institutional-relationship",
      "nation-and-historical-continuity",
      "foreign-policy-doctrine",
      "authority-democracy-and-subsidiarity",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "european-union-institutional-relationship",
    category: "nation",
    manifestoBasis: ["europe", "subsidiarity", "democracy"],
    related: [
      "europe-as-a-civilization-of-nations",
      "authority-democracy-and-subsidiarity",
      "nation-and-historical-continuity",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "economic-order",
    category: "economy",
    manifestoBasis: ["economic-order"],
    related: [
      "private-property-and-broad-ownership",
      "guilds-chambers-and-corporatist-representation",
      "finance-lending-and-usury",
      "work",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "private-property-and-broad-ownership",
    category: "economy",
    manifestoBasis: ["economic-order"],
    related: [
      "economic-order",
      "housing-and-financialization",
      "corporations-and-monopolies",
      "finance-lending-and-usury",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "corporations-and-monopolies",
    category: "economy",
    manifestoBasis: ["economic-order"],
    related: [
      "private-property-and-broad-ownership",
      "economic-order",
      "finance-lending-and-usury",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "guilds-chambers-and-corporatist-representation",
    category: "economy",
    manifestoBasis: ["corporatism", "subsidiarity"],
    related: [
      "economic-order",
      "work",
      "minimum-wage",
      "authority-democracy-and-subsidiarity",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "finance-lending-and-usury",
    category: "economy",
    manifestoBasis: ["finance"],
    related: [
      "housing-and-financialization",
      "private-property-and-broad-ownership",
      "gambling",
      "economic-order",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "housing-and-financialization",
    category: "economy",
    manifestoBasis: ["finance", "architecture"],
    related: [
      "private-property-and-broad-ownership",
      "finance-lending-and-usury",
      "family",
      "architecture-and-historic-preservation",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "work",
    category: "economy",
    manifestoBasis: ["work", "human-scale-life"],
    related: [
      "automation",
      "sunday-rest-and-trading",
      "guilds-chambers-and-corporatist-representation",
      "minimum-wage",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "minimum-wage",
    category: "economy",
    manifestoBasis: ["moral-order", "economic-order", "corporatism", "work"],
    related: [
      "work",
      "guilds-chambers-and-corporatist-representation",
      "trade-unions-and-vocational-representation",
      "taxation",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "taxation",
    category: "economy",
    manifestoBasis: [
      "family",
      "economic-order",
      "corporatism",
      "finance",
      "subsidiarity",
    ],
    related: [
      "family",
      "private-property-and-broad-ownership",
      "minimum-wage",
      "pensions",
      "housing-restrictions",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "pensions",
    category: "economy",
    manifestoBasis: [
      "family",
      "economic-order",
      "corporatism",
      "subsidiarity",
      "work",
    ],
    related: [
      "welfare-and-social-assistance",
      "family",
      "guilds-chambers-and-corporatist-representation",
      "taxation",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "housing-restrictions",
    category: "economy",
    manifestoBasis: ["family", "economic-order", "finance", "architecture"],
    related: [
      "housing-and-financialization",
      "private-property-and-broad-ownership",
      "architecture-and-historic-preservation",
      "taxation",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "trade-unions-and-vocational-representation",
    category: "economy",
    manifestoBasis: ["economic-order", "corporatism", "subsidiarity", "work"],
    related: [
      "guilds-chambers-and-corporatist-representation",
      "minimum-wage",
      "work",
      "corporations-and-monopolies",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "technology-general-doctrine",
    category: "technology",
    manifestoBasis: ["technology", "human-scale-life"],
    related: [
      "artificial-intelligence",
      "automation",
      "cash-and-non-digital-access",
      "right-to-repair",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "artificial-intelligence",
    category: "technology",
    manifestoBasis: ["technology"],
    related: [
      "automation",
      "surveillance",
      "technology-general-doctrine",
      "purpose-of-education",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "automation",
    category: "technology",
    manifestoBasis: ["technology", "work"],
    related: ["work", "artificial-intelligence", "technology-general-doctrine"],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "cash-and-non-digital-access",
    category: "technology",
    manifestoBasis: ["human-scale-life", "technology"],
    related: [
      "digital-identification",
      "central-bank-digital-currencies",
      "technology-general-doctrine",
      "surveillance",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "right-to-repair",
    category: "technology",
    manifestoBasis: ["technology", "stewardship"],
    related: [
      "technology-general-doctrine",
      "environmental-stewardship",
      "work",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "surveillance",
    category: "technology",
    manifestoBasis: ["human-scale-life", "technology"],
    related: [
      "artificial-intelligence",
      "facial-recognition",
      "communications-metadata-retention",
      "digital-identification",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "children-social-media-and-attention-capture",
    category: "technology",
    manifestoBasis: ["family", "technology", "human-scale-life", "education"],
    related: [
      "family",
      "pornography",
      "purpose-of-education",
      "technology-general-doctrine",
      "digital-identification",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "digital-identification",
    category: "technology",
    manifestoBasis: ["technology", "human-scale-life"],
    related: [
      "cash-and-non-digital-access",
      "surveillance",
      "central-bank-digital-currencies",
      "technology-general-doctrine",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "central-bank-digital-currencies",
    category: "technology",
    manifestoBasis: ["technology", "human-scale-life"],
    related: [
      "cash-and-non-digital-access",
      "digital-identification",
      "cryptocurrency",
      "finance-lending-and-usury",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "cryptocurrency",
    category: "technology",
    manifestoBasis: [
      "economic-order",
      "finance",
      "technology",
      "human-scale-life",
    ],
    related: [
      "central-bank-digital-currencies",
      "finance-lending-and-usury",
      "cash-and-non-digital-access",
      "private-property-and-broad-ownership",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "facial-recognition",
    category: "technology",
    manifestoBasis: ["technology", "human-scale-life"],
    related: [
      "surveillance",
      "communications-metadata-retention",
      "digital-identification",
      "technology-general-doctrine",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "communications-metadata-retention",
    category: "technology",
    manifestoBasis: ["technology", "human-scale-life", "subsidiarity"],
    related: [
      "surveillance",
      "facial-recognition",
      "digital-identification",
      "free-speech-and-public-doctrine",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "genetic-engineering",
    category: "technology",
    manifestoBasis: ["moral-order", "person-not-atom", "family", "technology"],
    related: [
      "transhumanism-and-human-enhancement",
      "catholic-medical-ethics",
      "abortion",
      "technology-general-doctrine",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "transhumanism-and-human-enhancement",
    category: "technology",
    manifestoBasis: [
      "moral-order",
      "person-not-atom",
      "technology",
      "human-scale-life",
    ],
    related: [
      "genetic-engineering",
      "technology-general-doctrine",
      "artificial-intelligence",
      "catholic-medical-ethics",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "purpose-of-education",
    category: "education",
    manifestoBasis: ["education"],
    related: [
      "state-schools-and-christianity",
      "private-catholic-and-independent-schools",
      "homeschooling",
      "universities-and-academic-freedom",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "homeschooling",
    category: "education",
    manifestoBasis: ["education", "family", "subsidiarity"],
    related: [
      "private-catholic-and-independent-schools",
      "purpose-of-education",
      "sex-education-in-schools",
      "family",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "private-catholic-and-independent-schools",
    category: "education",
    manifestoBasis: ["education", "subsidiarity"],
    related: [
      "homeschooling",
      "state-schools-and-christianity",
      "purpose-of-education",
      "universities-and-academic-freedom",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "universities-and-academic-freedom",
    category: "education",
    manifestoBasis: ["education", "democracy"],
    related: [
      "purpose-of-education",
      "free-speech-and-public-doctrine",
      "private-catholic-and-independent-schools",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "state-schools-and-christianity",
    category: "education",
    manifestoBasis: ["education", "moral-order"],
    related: [
      "catholic-confessional-state",
      "purpose-of-education",
      "private-catholic-and-independent-schools",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "sex-education-in-schools",
    category: "education",
    manifestoBasis: ["education", "family"],
    related: [
      "contraception",
      "homeschooling",
      "marriage-and-sexual-ethics",
      "family",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "culture-and-homogenization",
    category: "education",
    manifestoBasis: ["culture"],
    related: [
      "nation-and-historical-continuity",
      "architecture-and-historic-preservation",
      "purpose-of-education",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "architecture-and-historic-preservation",
    category: "education",
    manifestoBasis: ["architecture"],
    related: [
      "culture-and-homogenization",
      "housing-and-financialization",
      "environmental-stewardship",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "authority-democracy-and-subsidiarity",
    category: "government",
    manifestoBasis: ["subsidiarity", "democracy"],
    related: [
      "free-speech-and-public-doctrine",
      "europe-as-a-civilization-of-nations",
      "welfare-and-social-assistance",
      "high-public-office",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "free-speech-and-public-doctrine",
    category: "government",
    manifestoBasis: ["democracy", "moral-order"],
    related: [
      "blasphemy-and-sacrilege",
      "universities-and-academic-freedom",
      "pornography",
      "authority-democracy-and-subsidiarity",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "prisons-punishment-and-rehabilitation",
    category: "government",
    manifestoBasis: ["moral-order", "democracy"],
    related: [
      "criminal-sentencing",
      "death-penalty",
      "recreational-drugs",
      "firearms-and-self-defense",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "criminal-sentencing",
    category: "government",
    manifestoBasis: [
      "moral-order",
      "person-not-atom",
      "subsidiarity",
      "democracy",
      "what-we-reject",
    ],
    related: [
      "prisons-punishment-and-rehabilitation",
      "death-penalty",
      "capital-punishment-for-aggravated-sexual-crimes",
      "deportation-of-criminal-offenders",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "death-penalty",
    category: "government",
    manifestoBasis: ["moral-order"],
    related: [
      "capital-punishment-for-aggravated-sexual-crimes",
      "prisons-punishment-and-rehabilitation",
      "criminal-sentencing",
      "catholic-confessional-state",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "capital-punishment-for-aggravated-sexual-crimes",
    category: "government",
    manifestoBasis: ["moral-order", "democracy"],
    related: [
      "death-penalty",
      "criminal-sentencing",
      "prisons-punishment-and-rehabilitation",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "firearms-and-self-defense",
    category: "government",
    manifestoBasis: ["subsidiarity", "moral-order"],
    related: [
      "prisons-punishment-and-rehabilitation",
      "authority-democracy-and-subsidiarity",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "universal-healthcare-access",
    category: "healthcare",
    manifestoBasis: ["moral-order", "subsidiarity"],
    related: [
      "catholic-medical-ethics",
      "euthanasia-and-assisted-suicide",
      "welfare-and-social-assistance",
      "abortion",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "catholic-medical-ethics",
    category: "healthcare",
    manifestoBasis: ["moral-order"],
    related: [
      "abortion",
      "euthanasia-and-assisted-suicide",
      "contraception",
      "universal-healthcare-access",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "environmental-stewardship",
    category: "environment",
    manifestoBasis: ["stewardship"],
    related: [
      "energy-policy",
      "climate-policy",
      "right-to-repair",
      "architecture-and-historic-preservation",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "energy-policy",
    category: "environment",
    manifestoBasis: ["stewardship", "foreign-policy"],
    related: [
      "nuclear-energy",
      "fossil-fuels",
      "renewable-energy",
      "climate-policy",
      "environmental-stewardship",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "nuclear-energy",
    category: "environment",
    manifestoBasis: ["technology", "stewardship", "foreign-policy"],
    related: [
      "energy-policy",
      "fossil-fuels",
      "renewable-energy",
      "nuclear-weapons",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "fossil-fuels",
    category: "environment",
    manifestoBasis: ["stewardship", "foreign-policy"],
    related: [
      "energy-policy",
      "nuclear-energy",
      "renewable-energy",
      "climate-policy",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "renewable-energy",
    category: "environment",
    manifestoBasis: ["stewardship", "architecture"],
    related: [
      "energy-policy",
      "nuclear-energy",
      "fossil-fuels",
      "architecture-and-historic-preservation",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "climate-policy",
    category: "environment",
    manifestoBasis: ["technology", "stewardship", "foreign-policy"],
    related: [
      "energy-policy",
      "environmental-stewardship",
      "fossil-fuels",
      "renewable-energy",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "foreign-policy-doctrine",
    category: "foreign-policy",
    manifestoBasis: ["foreign-policy"],
    related: [
      "europe-as-a-civilization-of-nations",
      "nato",
      "conscription",
      "nuclear-weapons",
    ],
    lastUpdated: "2026-09-15",
  },
  {
    slug: "nato",
    category: "foreign-policy",
    manifestoBasis: ["foreign-policy", "subsidiarity", "what-we-reject"],
    related: [
      "foreign-policy-doctrine",
      "united-states",
      "russia",
      "conscription",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "russia",
    category: "foreign-policy",
    manifestoBasis: ["foreign-policy"],
    related: ["foreign-policy-doctrine", "ukraine", "nato", "sanctions"],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "ukraine",
    category: "foreign-policy",
    manifestoBasis: ["foreign-policy"],
    related: ["foreign-policy-doctrine", "russia", "nato", "foreign-aid"],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "united-states",
    category: "foreign-policy",
    manifestoBasis: ["europe", "technology", "culture", "foreign-policy"],
    related: [
      "foreign-policy-doctrine",
      "nato",
      "culture-and-homogenization",
      "china",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "china",
    category: "foreign-policy",
    manifestoBasis: ["economic-order", "technology", "foreign-policy"],
    related: [
      "foreign-policy-doctrine",
      "economic-order",
      "united-states",
      "digital-identification",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "israel-and-palestine",
    category: "foreign-policy",
    manifestoBasis: ["foreign-policy", "what-we-reject"],
    related: ["foreign-policy-doctrine", "foreign-aid", "sanctions"],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "foreign-aid",
    category: "foreign-policy",
    manifestoBasis: ["moral-order", "immigration", "foreign-policy"],
    related: [
      "foreign-policy-doctrine",
      "asylum-and-international-protection",
      "sanctions",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "sanctions",
    category: "foreign-policy",
    manifestoBasis: ["foreign-policy", "what-we-reject"],
    related: [
      "foreign-policy-doctrine",
      "russia",
      "foreign-aid",
      "israel-and-palestine",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "conscription",
    category: "foreign-policy",
    manifestoBasis: ["person-not-atom", "education", "work", "foreign-policy"],
    related: [
      "foreign-policy-doctrine",
      "nato",
      "purpose-of-education",
      "work",
    ],
    lastUpdated: "2026-09-21",
  },
  {
    slug: "nuclear-weapons",
    category: "foreign-policy",
    manifestoBasis: ["foreign-policy", "what-we-reject"],
    related: ["foreign-policy-doctrine", "nato", "nuclear-energy"],
    lastUpdated: "2026-09-21",
  },
] as const satisfies readonly PolicyEntryStructure[];

/**
 * Every slug, as a union. This is what makes a language file's catalogue
 * exhaustive: forget an entry and the build fails rather than one edition
 * quietly publishing ninety-seven positions where the others publish
 * ninety-eight.
 */
export type PolicySlug = (typeof policyStructure)[number]["slug"];

/**
 * The subjects the search's synonym map groups words under.
 *
 * An id is a handle for a concept, not a pointer at an entry. The language
 * files give each id the words a reader of that language would actually type
 * for the thing — `gay marriage` beside `same-sex marriage`, `nukes` beside
 * `nuclear weapons` — and the search widens a query to the rest of the group.
 * Which entry that reaches is decided by the catalogue's own text, so the map
 * never has to take a view about what a word implies, and adding a word here
 * cannot attach it to a position.
 *
 * The ids are structure, so they are the same in all six languages and the
 * type makes an edition that forgets one a build error. The *words* are not:
 * a group needs as many of them as its language needs, and the count
 * legitimately differs — which is why `scripts/check-translations.ts`
 * compares these lists by kind rather than by length.
 */
export const policySynonymGroupIds = [
  "church-and-state",
  "abortion",
  "euthanasia",
  "contraception",
  "same-sex-marriage",
  "pornography",
  "prostitution",
  "drugs",
  "alcohol",
  "gambling",
  "blasphemy",
  "family",
  "demography",
  "sunday-rest",
  "welfare",
  "nation",
  "immigration",
  "irregular-migration",
  "asylum",
  "deportation",
  "citizenship",
  "dual-citizenship",
  "integration",
  "voting",
  "european-union",
  "subsidiarity",
  "economy",
  "property",
  "monopolies",
  "corporatism",
  "usury",
  "housing",
  "work",
  "wages",
  "tax",
  "pensions",
  "unions",
  "technology",
  "artificial-intelligence",
  "automation",
  "cash",
  "right-to-repair",
  "surveillance",
  "facial-recognition",
  "social-media",
  "digital-identity",
  "central-bank-digital-currency",
  "cryptocurrency",
  "genetic-engineering",
  "transhumanism",
  "education",
  "homeschooling",
  "school-choice",
  "universities",
  "religion-in-schools",
  "sex-education",
  "culture",
  "architecture",
  "free-speech",
  "prisons",
  "death-penalty",
  "firearms",
  "healthcare",
  "medical-ethics",
  "environment",
  "energy",
  "nuclear-power",
  "fossil-fuels",
  "renewables",
  "climate",
  "defence",
  "nato",
  "russia",
  "ukraine",
  "united-states",
  "china",
  "israel-and-palestine",
  "foreign-aid",
  "sanctions",
  "conscription",
  "nuclear-weapons",
] as const;

export type PolicySynonymGroupId = (typeof policySynonymGroupIds)[number];
