import { europeContext, europeViewBox, europeWings } from "@/content/wings-map";
import { cn } from "@/lib/utils";

interface EuropeMapProps {
  readonly className?: string;
  /** Describes the map to anyone who cannot see it. */
  readonly label: string;
}

/**
 * The continent, with the forty-four nations that carry a wing picked out.
 *
 * Deliberately not interactive, and deliberately hidden from assistive
 * technology. The grid immediately below this map is the same information as
 * forty-four real links, so making the countries clickable would duplicate
 * every one of them in the tab order and read out a second time — and it would
 * hand the smallest wings a hit area of a few pixels. The map's job here is to
 * make "there is no wing where I live" legible at a glance, which is a job for
 * the eye. The list does the rest.
 *
 * Geometry comes from `content/wings-map.ts`, which is generated by
 * `npm run map` from Natural Earth data. Colour is applied here rather than
 * baked in, so the map follows the design tokens like everything else.
 */
export function EuropeMap({ className, label }: EuropeMapProps) {
  return (
    <svg
      viewBox={europeViewBox}
      role="img"
      aria-label={label}
      className={cn("h-auto w-full", className)}
    >
      {/*
       * Land without a wing. It has to be visible enough that the Mediterranean
       * reads as a sea rather than as the edge of the picture, and quiet enough
       * that it is not mistaken for a wing.
       *
       * Both kinds of land are tinted from the same gold, and separate by value
       * alone. The palette's neutrals are all cool, so using one of them here
       * put a blue Belarus and a blue Anatolia against a warm Europe, and the
       * map read as two clashing pictures rather than one with something
       * highlighted in it.
       */}
      <path d={europeContext} className="fill-gold/6 stroke-hairline" strokeWidth={4} />

      {europeWings.map((wing) => (
        <path key={wing.slug} d={wing.d} className="fill-gold/28 stroke-canvas" strokeWidth={5} />
      ))}

      {/*
       * Andorra, Liechtenstein, Malta, Monaco and San Marino are a few pixels
       * across at this scale. Without a marker they would be indistinguishable
       * from the sea or from a neighbour, which would read as five nations left
       * off the map.
       */}
      {europeWings
        .filter((wing) => wing.small)
        .map((wing) => (
          <circle key={wing.slug} cx={wing.cx} cy={wing.cy} r={26} className="fill-gold/70" />
        ))}
    </svg>
  );
}
