import Link from "next/link";
import type { Wing, WingsEdition } from "@/content/wings";
import { europeContext, europeViewBox, europeWings, type MappedWing } from "@/content/wings-map";
import { localePath } from "@/lib/i18n";
import { cn } from "@/lib/utils";

interface EuropeMapProps {
  readonly edition: WingsEdition;
  readonly className?: string;
}

/**
 * Where the hovered country's name is written, in `viewBox` units.
 *
 * One fixed slot rather than a label at each country's centroid. A centroid
 * label is drawn inside its own `<a>`, and SVG has no `z-index`: whichever
 * nation is later in document order paints over it, so Albania's name would be
 * buried under Montenegro and Greece. A single slot is also steadier to read —
 * the name always appears in the same place instead of chasing the pointer.
 *
 * The slot is the empty north Atlantic above Iceland. `x` up to 1070 and `y` up
 * to 300 is the largest rectangle in this frame that no wing outline reaches
 * (the nearest is the Norwegian coast at x 1081), so the name is never drawn
 * over land whatever order the nations happen to be in.
 */
const LABEL = { x: 68, baseline: 214, size: 88 } as const;

/** Radius of the invisible hit target given to a nation a few pixels across. */
const MARKER_TARGET = 90;

/**
 * The continent, with the forty-seven nations that carry a wing picked out, each
 * one a link to its own page.
 *
 * A Server Component, and it has to stay one: `content/wings-map.ts` is 42 kB
 * of path data, already shipped once as markup, and a `"use client"` boundary
 * would send it a second time as JavaScript. Every state below is therefore
 * plain CSS on the `<a>` — `:hover` and `:focus-visible` through Tailwind's
 * `group-*` variants — which also means the map works before hydration and
 * without JavaScript at all.
 *
 * **On the accessibility tree.** The map is *not* `aria-hidden`. That would have
 * been the cheaper answer — the grid below is the same forty-seven nations as
 * real links, so a decorative map plus that list is a defensible accessible
 * equivalent, and it is what this component used to do. It was rejected because
 * the map is now a control: `aria-hidden` may not contain focusable elements, so
 * hiding it would mean taking the outlines out of the tab order, leaving a map a
 * mouse can operate and a keyboard cannot. The cost is that a screen reader
 * reads the nations twice, once here and once in the grid; the `role="group"`
 * with a name is what lets someone recognise this copy and skip it.
 *
 * Each `<a>` is named by a `<title>`, which serves twice: it is the accessible
 * name, and it is the native tooltip for a pointer user. The visible label in
 * the slot above is `aria-hidden`, being a second rendering of the same word.
 *
 * In forced-colours mode the fills stop carrying meaning and the grid below is
 * the operable copy.
 *
 * Geometry comes from `content/wings-map.ts`, which is generated by
 * `npm run map` from Natural Earth data. Colour is applied here rather than
 * baked in, so the map follows the design tokens like everything else. Country
 * names come from the edition, never from the generated data, so the map is
 * translated with the rest of the page.
 */
export function EuropeMap({ edition, className }: EuropeMapProps) {
  const shapes = new Map(europeWings.map((shape) => [shape.slug, shape]));

  /*
   * The generator hard-errors on a wing it cannot find an outline for, so the
   * filter never drops anything; it is here to narrow the type.
   *
   * `edition.wings` is already collated in the reader's own language, which is
   * the order the grid below uses, so the tab order through the map matches it.
   * The five nations a few pixels across are moved to the end because paint
   * order is not negotiable: their markers and enlarged hit targets have to sit
   * *above* the neighbours that surround them, or France swallows Monaco and
   * Andorra both. It also puts the five fiddliest targets somewhere predictable
   * rather than scattered through the other forty-two.
   */
  const drawn = edition.wings
    .map((wing) => ({ wing, shape: shapes.get(wing.slug) }))
    .filter((entry): entry is { wing: Wing; shape: MappedWing } => entry.shape !== undefined)
    .sort((a, b) => Number(a.shape.small) - Number(b.shape.small));

  return (
    <svg
      viewBox={europeViewBox}
      role="group"
      aria-label={edition.meta.mapLabel}
      className={cn("h-auto w-full", className)}
    >
      {/*
       * Land without a wing. It has to be visible enough that the Mediterranean
       * reads as a sea rather than as the edge of the picture, and quiet enough
       * that it is not mistaken for a wing.
       *
       * Both kinds of land are tinted from the same gold, and separate by value
       * alone. The palette's neutrals are all cool, so using one of them here
       * put a blue Belarus and a blue Anatolia against a warm Europe, and the
       * map read as two clashing pictures rather than one with something
       * highlighted in it.
       *
       * Inert, and explicitly so: there is no wing to go to, so it must not
       * take the pointer or offer a cursor that suggests otherwise.
       */}
      <path
        d={europeContext}
        className="pointer-events-none fill-gold/6 stroke-hairline"
        strokeWidth={4}
      />

      {drawn.map(({ wing, shape }) => (
        <Link
          key={wing.slug}
          href={localePath(edition.locale, `/wings/${wing.slug}`)}
          /*
           * The site's global focus ring is suppressed here, and replaced
           * below, because an outline on an SVG element is drawn around the
           * bounding box of the whole link. That box spans the label slot in
           * the north Atlantic as well as the country, so the ring would be a
           * rectangle across half the map pointing at nothing. What replaces it
           * is shaped like the nation itself: the fill lifts, a parchment edge
           * is drawn round it, and its name appears in the slot.
           */
          className="group cursor-pointer focus-visible:outline-none"
        >
          <title>{wing.country}</title>

          <path
            d={shape.d}
            strokeWidth={5}
            className="fill-gold/28 stroke-canvas transition-colors group-hover:fill-burgundy/70 group-focus-visible:fill-burgundy/70 group-focus-visible:stroke-ink group-focus-visible:[stroke-width:20]"
          />

          {/*
           * Andorra, Liechtenstein, Malta, Monaco and San Marino are a few
           * pixels across at this scale. Without a marker they would be
           * indistinguishable from the sea or from a neighbour, which would
           * read as five nations left off the map — and without a hit target
           * larger than the outline they would be unclickable as well. The
           * ring, which only appears on hover or focus, is what makes a
           * five-pixel dot legible as the thing that is about to be opened.
           */}
          {shape.small ? (
            <>
              <circle
                cx={shape.cx}
                cy={shape.cy}
                r={MARKER_TARGET}
                className="fill-transparent"
              />
              <circle
                cx={shape.cx}
                cy={shape.cy}
                r={26}
                className="fill-gold/70 transition-colors group-hover:fill-burgundy group-focus-visible:fill-burgundy"
              />
              <circle
                cx={shape.cx}
                cy={shape.cy}
                r={72}
                strokeWidth={14}
                className="pointer-events-none fill-none stroke-burgundy opacity-0 transition-opacity group-hover:opacity-100 group-focus-visible:opacity-100"
              />
            </>
          ) : null}

          {/*
           * Hidden below `sm`, where the plate is barely three hundred pixels
           * wide and text that scales with the map would be five pixels tall.
           * Nothing is lost: a touch reader has no hover state to read a name
           * in, and tapping goes straight to the page that is named after it.
           *
           * `pointer-events-none` matters more than it looks. Forty-seven of
           * these sit in the same corner at zero opacity, and an invisible
           * `<text>` still answers the pointer — without this the north
           * Atlantic would be a stack of links to whichever nation happened to
           * be on top.
           */}
          <text
            x={LABEL.x}
            y={LABEL.baseline}
            fontSize={LABEL.size}
            aria-hidden="true"
            className="pointer-events-none fill-ink font-serif opacity-0 transition-opacity group-hover:opacity-100 group-focus-visible:opacity-100 max-sm:hidden"
          >
            {wing.country}
          </text>
        </Link>
      ))}
    </svg>
  );
}
