/**
 * The mark's geometry, as `components/brand/RestoreEuropaMark.tsx` needs it.
 *
 * Generated by `scripts/generate-brand.mjs`. Change the constants there and
 * run `npm run brand`; editing this file only means the on-site mark and the
 * icons stop agreeing with each other.
 */

export const markViewBox = "0 0 1024 1024";

export const markLozenge = "M491.18 39H532.82L985 491.18V532.82L532.82 985H491.18L39 532.82V491.18ZM512 81.82L942.18 512L512 942.18L81.82 512Z";

export const markRects = [
  { x: 459, y: 39, width: 106, height: 946 },
  { x: 39, y: 459, width: 946, height: 106 },
  { x: 355, y: 39, width: 314, height: 65 },
  { x: 355, y: 920, width: 314, height: 65 },
  { x: 39, y: 355, width: 65, height: 314 },
  { x: 920, y: 355, width: 65, height: 314 },
] as const;
